name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código 2
      - name: Checkout code
        uses: actions/checkout@v3

      # Verificar estructura del proyecto
      - name: Debug environment
        run: |
          echo "Current Directory: $(pwd)"
          ls -R
          echo "PYTHONPATH: $PYTHONPATH"
          python -c "import sys; print('Sys Path:', sys.path)"

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecutar pruebas
      - name: Run tests
        run: python run_tests.py  # Alternativa 1: usar run_tests.py

      # Ejecutar el script principal
      - name: Run app script
        run: python src/main.py
